# Max number of shortcuts
MAX_KEYS=9

# Custom Plank directory (Optional) 
# Uncomment and update path below if custom setup is used for launchers or multiple docks are present
# PLANK_DIR="$HOME/.config/plank/dock1/launchers"
